version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"  # AMQP port
      - "15672:15672"  # Management UI port
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 3

  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=shopit
      - POSTGRES_HOST_AUTH_METHOD=scram-sha-256
    command: ["postgres", "-c", "password_encryption=scram-sha-256"]
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d shopit"]
      interval: 5s
      timeout: 5s
      retries: 3

  mailpit:
    image: axllent/mailpit:latest
    platform: linux/arm64
    ports:
      - "1026:1025"  # SMTP server port (mapped to different host port)
      - "8026:8025"  # Web UI port (mapped to different host port)
    environment:
      MP_MAX_MESSAGES: "500"
      MP_DATABASE: "/data/mailpit.db"
      MP_SMTP_AUTH_ACCEPT_ANY: "true"
    command: ["--smtp-auth-allow-insecure"]
    volumes:
      - mailpit_data:/data
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "1025"]
      interval: 5s
      timeout: 5s
      retries: 3

volumes:
  rabbitmq_data:
  redis_data:
  postgres_data:
  mailpit_data:
  # Explicitly name volumes for better clarity
